version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/www.conf
      - ../html/dist:/home
      - ../php/upload:/home/upload
      - ../ssl:/etc/nginx/ssl

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../data:/data

  php:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai
    command: -f Client.php -- -p 8080 -n 4
    depends_on: [redis]
    sysctls:
      - net.core.somaxconn=40960
    volumes:
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ../php:/home/
      - ../ssl:/home/ssl

networks:
  my-web:
    driver_opts:
      com.docker.network.driver.mtu: 1492
