version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/www.conf
      - /home/chat/html_v2/dist:/home

  redis:
    image: redis:latest
    ports:
      - 6379
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/chat/data:/data

  php:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-web
    environment:
      - TZ=Asia/Shanghai
    command: -f Client.php -- -p 8080 -n 4
    depends_on: [redis]
    sysctls:
      - net.core.somaxconn=40960
    volumes:
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /home/chat/php:/home/

networks:
  my-web:
    driver_opts:
      com.docker.network.driver.mtu: 1492
